image: gcc:10.2

pipelines:
  default:
    - step:
        name: prepare
        script:
          - apt update -y
          - apt install cmake -y
    - step:
        name: build
        script:
          - make test
    - step:
        name: Run coverage
        script:
          - mmake coverage
