image: gcc:10.2

pipelines:
  default:
    - parallel:
        - step:
            name: build
            script:
              - make test
        - step:
            name: Run coverage
            script:
              - mmake coverage
