image: gcc:10.2

pipelines:
  default:
    - step:
        name: build and test
        script:
          - apt update -y
          - apt install cmake -y
          - make test
          - make coverage
